# Generated by Django 4.0.1 on 2022-01-26 19:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dcm_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='metaverseavatar',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='metaverseavatar', to='dcm_app.metaverseavatar'),
        ),
    ]
