# Generated by Django 4.0.1 on 2022-01-27 22:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dcm_app', '0002_character_metaverseavatar'),
    ]

    operations = [
        migrations.CreateModel(
            name='NFT',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('image_url', models.URLField()),
                ('current_bid', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Observation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=128)),
                ('text', models.TextField(max_length=1000)),
            ],
        ),
        migrations.RenameModel(
            old_name='MetaverseAvatar',
            new_name='Avatar',
        ),
        migrations.DeleteModel(
            name='Character',
        ),
        migrations.AddField(
            model_name='nft',
            name='avatar',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='avatar', to='dcm_app.avatar'),
        ),
    ]
