# Generated by Django 4.0.1 on 2022-01-28 19:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dcm_app', '0003_nft_observation_rename_metaverseavatar_avatar_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='nft',
            name='auction_duration',
            field=models.DurationField(choices=[('one_day', '1 Day'), ('two_days', '2 Days'), ('three_days', '3 Days'), ('four_days', '4 Days'), ('five_days', '5 Days'), ('six_days', '6 Days'), ('one-week', '1 Week'), ('two_weeks', '2 Weeks'), ('three_weeks', '3 Weeks'), ('four_weeks', '4 Weeks'), ('five_weeks', '5 Weeks'), ('six_weeks', '6 Weeks'), ('eight_weeks', '8 Weeks'), ('twelve_weeks', '12 Weeks')], null=True),
        ),
        migrations.AddField(
            model_name='nft',
            name='start_date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
