# Generated by Django 4.0.1 on 2022-01-28 23:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dcm_app', '0004_nft_auction_duration_nft_start_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nft',
            name='auction_duration',
        ),
    ]
