# Generated by Django 4.0.1 on 2022-01-28 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dcm_app', '0005_remove_nft_auction_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nft',
            name='image_url',
            field=models.CharField(max_length=200),
        ),
    ]
