# Generated by Django 4.0.1 on 2022-01-30 00:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dcm_app', '0006_alter_nft_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='observation',
            name='nfts',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='nft', to='dcm_app.nft'),
        ),
        migrations.AlterField(
            model_name='nft',
            name='image_url',
            field=models.URLField(),
        ),
    ]
