# Generated by Django 4.0.1 on 2022-01-30 08:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dcm_app', '0013_nft_observations'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='observation',
            options={'ordering': ['text']},
        ),
        migrations.RemoveField(
            model_name='nft',
            name='observations',
        ),
        migrations.AddField(
            model_name='observation',
            name='nft',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='observations', to='dcm_app.nft'),
            preserve_default=False,
        ),
    ]
