# Generated by Django 4.0.1 on 2022-01-30 08:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dcm_app', '0014_alter_observation_options_remove_nft_observations_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='observation',
            options={},
        ),
        migrations.AlterField(
            model_name='observation',
            name='nft',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nfts', to='dcm_app.nft'),
        ),
    ]
