# Generated by Django 4.0.1 on 2022-01-30 08:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dcm_app', '0015_alter_observation_options_alter_observation_nft'),
    ]

    operations = [
        migrations.AlterField(
            model_name='observation',
            name='nft',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='observations', to='dcm_app.nft'),
        ),
    ]
