# Generated by Django 4.0.1 on 2022-01-30 18:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dcm_app', '0016_alter_observation_nft'),
    ]

    operations = [
        migrations.RenameField(
            model_name='observation',
            old_name='username',
            new_name='name',
        ),
    ]
