# Generated by Django 4.0.1 on 2022-01-30 19:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dcm_app', '0017_rename_username_observation_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='observation',
            name='nft',
        ),
        migrations.AddField(
            model_name='nft',
            name='observations',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='observation', to='dcm_app.observation'),
        ),
    ]
