# Generated by Django 4.0.1 on 2022-01-30 19:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dcm_app', '0018_remove_observation_nft_nft_observations'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nft',
            name='observations',
        ),
    ]
