# Generated by Django 4.0.1 on 2022-01-31 00:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dcm_app', '0021_nft_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='observation',
            name='nft',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='observations', to='dcm_app.nft'),
        ),
    ]
