# Generated by Django 4.0.1 on 2022-01-31 04:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dcm_app', '0022_alter_observation_nft'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nft',
            name='owner',
        ),
        migrations.AlterField(
            model_name='nft',
            name='avatar',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='nfts', to='dcm_app.avatar'),
        ),
    ]
