# Generated by Django 4.0.1 on 2022-01-26 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('image_url', models.URLField()),
                ('current_bid', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='MetaverseAvatar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=128)),
                ('email_address', models.EmailField(max_length=254)),
            ],
        ),
    ]
